import { Bird } from './types';

export const BIRDS: Bird[] = [
  {
    id: 'rotkehlchen',
    germanName: 'Rotkehlchen',
    englishName: 'European Robin',
    description: 'A small insectivorous passerine bird with an orange-red breast.',
    category: 'garden',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Robin_%289509442456%29.jpg',
  },
  {
    id: 'amsel',
    germanName: 'Amsel',
    englishName: 'Blackbird',
    description: 'Black plumage and yellow bill. Known for its beautiful song.',
    category: 'garden',
    imageUrl: 'https://de.wikipedia.org/wiki/Datei:Common_Blackbird.jpg',
  },
  {
    id: 'blaumeise',
    germanName: 'Blaumeise',
    englishName: 'Blue Tit',
    description: 'Identifiable by its blue and yellow plumage and small size.',
    category: 'garden',
    imageUrl: 'https://images.unsplash.com/photo-1543333995-a78ee9e54201?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'kohlmeise',
    germanName: 'Kohlmeise',
    englishName: 'Great Tit',
    description: 'Larger than the blue tit, with a prominent black stripe on its yellow chest.',
    category: 'garden',
    imageUrl: 'https://images.unsplash.com/photo-1492416955325-132d78701e67?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'elster',
    germanName: 'Elster',
    englishName: 'Magpie',
    description: 'Striking black and white bird with long tail and iridescent feathers.',
    category: 'garden',
    imageUrl: 'https://images.unsplash.com/photo-1616422891969-952089204c35?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'eichelhaeher',
    germanName: 'Eichelhäher',
    englishName: 'Eurasian Jay',
    description: 'Colorful forest bird, famously known for burying acorns.',
    category: 'forest',
    imageUrl: 'https://images.unsplash.com/photo-1518992028580-6d57bd80f2dd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'buntspecht',
    germanName: 'Buntspecht',
    englishName: 'Great Spotted Woodpecker',
    description: 'Bold black and white plumage with a red vent and (in males) a red nape.',
    category: 'forest',
    imageUrl: 'https://images.unsplash.com/photo-1565551390426-34d1bc945417?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'turmfalke',
    germanName: 'Turmfalke',
    englishName: 'Common Kestrel',
    description: 'A falcon species that can often be seen hovering over fields.',
    category: 'predator',
    imageUrl: 'https://images.unsplash.com/photo-1534067783941-51c9c23eccfd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'dompfaff',
    germanName: 'Dompfaff',
    englishName: 'Bullfinch',
    description: 'Striking bird with a bright pink-red breast and a black cap.',
    category: 'forest',
    imageUrl: 'https://images.unsplash.com/photo-1620131490278-df0962776fc9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'kleiber',
    germanName: 'Kleiber',
    englishName: 'Eurasian Nuthatch',
    description: 'The only European bird that can climb down tree trunks headfirst.',
    category: 'forest',
    imageUrl: 'https://images.unsplash.com/photo-1616147290533-3d964de62f7f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'bachstelze',
    germanName: 'Bachstelze',
    englishName: 'White Wagtail',
    description: 'A slender, black and white bird known for its constant tail-wagging.',
    category: 'water',
    imageUrl: 'https://images.unsplash.com/photo-1555412654-72a95a495858?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'mauersegler',
    germanName: 'Mauersegler',
    englishName: 'Common Swift',
    description: 'Spends almost its entire life in the air, even sleeping while flying.',
    category: 'garden',
    imageUrl: 'https://images.unsplash.com/photo-1621516428469-caef6c79a770?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
];
